services:
  backend:
    build:
      context: ./back  # Diretório do backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=cme
      - DJANGO_SETTINGS_MODULE=backendCME.settings
    depends_on:
      - db
    command: >
      sh -c "pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./front/frontcme  # Diretório do frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./front/frontcme:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: >
      sh -c "npm install && npm run dev"

  db:
    image: postgres:13
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=cme
    ports:
      - "5432:5432"

volumes:
  postgres_data:
